### ISSUE TITLE
Add image loading class

### ISSUE THREAD

**Issue by markediez** [dssit/marchand#7]
When an image is still loading, we can follow facebook's style of some gray background while the image loads

**Comment by shanglu9425** [comment]
created class call "image-placeholder":
<div class="image-placeholder">
	<img src="https://thumb7.shutterstock.com/display_pic_with_log3.jpg" alt="Smiley face">
</div>

**Comment by shanglu9425** [comment]
<div class="image-placeholder">
					<img src="https://thumb7.shutterstock.com/display_pic_with_logo/64260/405078397/stock-photo-business-architecture-building-construction-and-people-concept-close-up-of-architect-hands-405078397.jpg" alt="Smiley face">
				</div>
